# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d04aa44be9cbedda3847566ae9cc5451cb8e56ec9916ffa4d2e8c5998ae96a164122e736204de1f8e03c72813e2f1ece9615b0ad9325c8eb581b587cedb3672

test:
  secret_key_base: d466040cf083d63e83f3c1a9f2ac6e7bc87dbf6bdf2f119b270b8e1f1085f0d42ad6dfd0d19e89ecaea7e4301715273bdd7fec32da1d60de4a27db7b5a0ff052

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
